sudo: true

language: cpp

cache: ccache

os:
  - osx

osx_image: xcode9.4

env:
  - TASK=python_test

matrix:
  include:
    - os: osx

before_install:
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python

install:
  - brew install ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - source ci/travis/install.sh

script:
  - mv make/osx.mk config.mk
  - make -j 2
  - python -m nose --verbose tests/python/unittest/
