version: 2
jobs:
    build:
        macos:
             xcode: "8.3.3"
        steps:
        - checkout
        - run:
            name: Really checkout
            command: 'git submodule update --init --recursive'
        - run:
              name: Updated Brew
              command: 'brew update'
        - run:
            name: Install opencv
            command: 'brew install opencv'
        - run:
              name: Install python3
              command: 'brew install python3'
        - run:
              name: Install fftw
              command: 'brew install fftw'
        - run:
              name: Install libpng
              command: 'brew install libpng'
        - run:
              name: Install ImageMagick
              command: 'brew install ImageMagick'
        - run:
              name: Install swig
              command: 'brew install swig'
        - run:
            name: Install python packages
            command: 'python -m pip install --user nose numpy cython scipy'
        - run:
            name: Copy default MacOS config
            command: 'mv make/osx.mk config.mk'
        - run:
            name: Compile
            command: 'make -j 4'
