version: 2
jobs:
    build:
        macos:
             xcode: "8.3.3"
        steps:
        - checkout
        - run:
              name: Updated Brew
              command: 'brew install opencv'
        - run:
              name: Install python3
              command: 'brew install python3'
        - run:
              name: Install fftw
              command: 'brew install fftw'
        - run:
              name: Install libpng
              command: 'brew install libpng'
        - run:
              name: Install ImageMagick
        - run:
              name: Install swig
              command: 'brew install swig'
